'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.handleAsyncError = undefined;

var _log = require('./log');

const handleAsyncError = exports.handleAsyncError = (asyncFn, errorHandler = _log.logError) => argv => {
  return asyncFn(argv).catch(error => {
    errorHandler(error);
    // Since the error got catched to allow async commands in yargs
    // and we can't throw to avoid unresolved promise rejections,
    // we manually exit here with exit code 1
    process.exit(1);
  });
};